import axios from 'axios'
import jsonwebtoken from 'jsonwebtoken'
require('dotenv').config()


export default class Github{
  constructor(){
    this.token = process.env.GITHUB_APIKEY
    this.defaultOrg = process.env.GITHUB_ORG
  }
  
  /**
   * 
   * @param {String} route - route to use on Github REST API
   */
   async restRequest(route){
   return axios({
      method: 'get',
      url: `https://api.github.com${route}`,
     
      headers: { 'Authorization': `bearer ${this.token}`}
    }).then(data => data.data)
  }

  /**
   * 
   * @param {String} query - GraphQl query  
   */
  async graphQlRequest(query){
    const response = await axios({
    method: 'post',
    url: 'https://api.github.com/graphql',
    headers: {
      'Authorization': `bearer ${this.token}`
    },
    data: {
      query
    }
  }).then(data => data.data)


  return response
  }
  
  async getOrgRepos(org = this.defaultOrg, list = [], cursor){
    const query = `{
      organization(login: ${org}) {
        login
        repositories(first: 100 ${cursor ? ',after: "' + cursor + '"' : ''}) {
          pageInfo {
            hasNextPage
            endCursor
          }
          nodes {
            name
            isPrivate
          }
        }    
      }
    }`
    
    const response = await this.graphQlRequest(query).then(data => data.data)
    list = [...list, ...response.organization.repositories.nodes]
    if(response.organization.repositories.pageInfo.hasNextPage){
      return this.getOrgRepos(org, list, response.organization.repositories.pageInfo.endCursor)
    }

    return {
      organization: org,
      repositories: list
    }

  }
  /**
   * 
   * @param {String} org - Github organization name 
   * @param {String} repo - Github repository name
   */
   async getRepositoryCollaborators(repo){
    const route = `/repos/${this.defaultOrg}/${repo}/collaborators`
    const response = await this.restRequest(route)
  
    return response
  }
  

  /**
   * 
   * @param {String} repo - Repository to retrieve information 
   * @param {*} org - organization/user repository owner
   */
   async getRepositoryInformation(repo, org = this.defaultOrg, ){
    const route = `/repos/${org}/${repo}`
    const response = await this.restRequest(route)
  
    return response
  }
  
  /**
   * 
   * @param {String} repoName - Github  repository name (dataset)
   * @param {Array} collaborators - List of repository collaborators
   */
   parserCollaboratorsList(repoName, collaborators){
   const dataScope = {
       organization: this.defaultOrg,
       dataset: repoName, 
       editors: [],
       readers: [],
       admin: []
     }
  
     collaborators.map(user => {
       if(user.permissions.push) dataScope.editors.push(user.login)
       if(user.permissions.pull) dataScope.readers.push(user.login)
       if(user.permissions.admin) dataScope.admin.push(user.login)
     })
  
     return dataScope
  }
  
  /**
   * 
   * @param {String} requestScope - repository scope requested
   */
   isValidScope(dataset, requestScope){
   const validScopes = ['read', 'write', 'admin']
    if(!validScopes.includes(requestScope)) {
      throw new Error(`Invalid scope. Scope should be of form "${this.defaultOrg}/${dataset}:read/write/admin"`)
    }
  }
  
  /**
   * Refactor this method using file generated by script
   * @param {String} dataset - Github depository name 
   * @param {String} user - Username logged in
   */
   async getScopes(dataset, user){
   
  }

}  


